# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 Ericsson and the Erlang/OTP contributors

[build_info]
apps = [
    "lib/*",
    {"name" = "erts", "dir" = "erts/preloaded", "src_dirs" = ["src"], "include_dirs" = ["../../lib/kernel/src", "../../lib/kernel/include"]},
    {"name" = "wx", "dir" = "lib/wx", "src_dirs" = ["src", "gen"], "include_dirs" = ["include"]},
    {"name" = "inets", "dir" = "lib/inets", "src_dirs" = ["src/http_client", "src/http_server", "src/http_lib", "src/inets_app"], "include_dirs" = ["include"]},
    {"name" = "common_test", "dir" = "lib/common_test", "src_dirs" = ["src", "test_server"], "include_dirs" = ["include", "../snmp/include", "../kernel/include"]},
    # Due to some Erlang/OTP bootstrapping issues, `stdlib` modules such as `gen_server` includes headers from the kernel application
    # using a simple `-include` directive, causing ELP to fail resolving those inclusions.
    # Include kernel as an `include_dir` for `stdlib` to solve the issue
    {"name" = "stdlib", "dir" = "lib/stdlib", "include_dirs" = ["include", "../kernel/include"]},
    {"name" = "dialyzer", "dir" = "lib/dialyzer", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["include", "src", ""], "macros" = {"VSN" = "DEFAULT_VSN"}},
    {"name" = "snmp", "dir" = "lib/snmp", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["include", "src", "", "src/misc", "src/compile", "src/app"], "macros" = {"default_verbosity"="silence", "version"="version"}},
    {"name" = "sasl", "dir" = "lib/sasl", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["include", "src", "", "../stdlib/include"], "macros" = {}},
    {"name" = "compiler", "dir" = "lib/compiler", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["include", "src", "", "../stdlib/include"], "macros" = {"COMPILER_VSN"="COMPILER_VSN"}},
    # yecc.erl - -include("erl_compile.hrl").
    {"name" = "parsetools", "dir" = "lib/parsetools", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["include", "src", "", "../stdlib/include"], "macros" = {"COMPILER_VSN"="COMPILER_VSN"}},
    # ELDAPv3.hrl is generated in ebin
    {"name" = "eldap", "dir" = "lib/eldap", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["include", "src", "", "ebin"], "macros" = {}},
    {"name" = "observer", "dir" = "lib/observer", "src_dirs" = ["src"], "extra_src_dirs" = ["test"], "include_dirs" = ["include", "src", "", "../et/include"], "macros" = {}},
    ]
deps = []

[eqwalizer]
enable_all = true
max_tasks = 4
