#!/bin/bash

~/code/elp eqwalize erl_lint erl_lint erl_expand_records core_lib v3_core beam_utils erl_bifs erl_internal core_pp beam_ssa beam_core_to_ssa sys_core_bsm beam_disasm
# cerl sys_core_fold
